<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'sku'                 => 'FAC-001',
                'name'                => 'Horn Cover Sprint S',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Sprint S'],
                'modal_price'         => 306200,
                'reseller_price'      => 352000,
                'online_price'        => 375000,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-002',
                'name'                => 'Horn Cover Sprint S',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['Sprint S'],
                'modal_price'         => 336200,
                'reseller_price'      => 387000,
                'online_price'        => 375000,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-003',
                'name'                => 'Mini Shield',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Universal'],
                'modal_price'         => 128800,
                'reseller_price'      => 149000,
                'online_price'        => 150000,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-004',
                'name'                => 'Mini Shield',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['Universal'],
                'modal_price'         => 138800,
                'reseller_price'      => 160000,
                'online_price'        => 150000,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-005',
                'name'                => 'Spark Plug Cover Sprint',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['Sprint'],
                'modal_price'         => 184200,
                'reseller_price'      => 212000,
                'online_price'        => null,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-006',
                'name'                => 'Spoiler Plug Sprint',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Sprint'],
                'modal_price'         => 49900,
                'reseller_price'      => 58000,
                'online_price'        => 58000,
                'current_stock'       => 2,
            ],
            [
                'sku'                 => 'FAC-007',
                'name'                => 'Spoiler Plug LX',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['LX'],
                'modal_price'         => 49900,
                'reseller_price'      => 58000,
                'online_price'        => null,
                'current_stock'       => 4,
            ],
            [
                'sku'                 => 'FAC-008',
                'name'                => 'Mounting Cover',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Universal'],
                'modal_price'         => 117900,
                'reseller_price'      => 136000,
                'online_price'        => 119000,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-009',
                'name'                => 'Mounting Cover',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['Universal'],
                'modal_price'         => 127900,
                'reseller_price'      => 147000,
                'online_price'        => 119000,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-010',
                'name'                => 'Rem Handle Set',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Universal'],
                'modal_price'         => 444300,
                'reseller_price'      => 511000,
                'online_price'        => null,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-011',
                'name'                => 'Shock Cover Sprint',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Sprint'],
                'modal_price'         => 127900,
                'reseller_price'      => 148000,
                'online_price'        => null,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-012',
                'name'                => 'Shock Cover Sprint',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['Sprint'],
                'modal_price'         => 147900,
                'reseller_price'      => 170000,
                'online_price'        => null,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-013',
                'name'                => 'Shock Cover LX/S',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['LX S'],
                'modal_price'         => 127900,
                'reseller_price'      => 148000,
                'online_price'        => 139000,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-014',
                'name'                => 'Shock Cover LX/S',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['LX S'],
                'modal_price'         => 147900,
                'reseller_price'      => 170000,
                'online_price'        => 139000,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-015',
                'name'                => 'Fork Cover',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Universal'],
                'modal_price'         => 198300,
                'reseller_price'      => 228000,
                'online_price'        => 235000,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-016',
                'name'                => 'Fork Cover',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['Universal'],
                'modal_price'         => 208300,
                'reseller_price'      => 240000,
                'online_price'        => 235000,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-017',
                'name'                => 'Glovebox Cup Sprint',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Sprint'],
                'modal_price'         => 448500,
                'reseller_price'      => 516000,
                'online_price'        => 600000,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-018',
                'name'                => 'Horn Cover Sprint 2024',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['Sprint 2024'],
                'modal_price'         => 290900,
                'reseller_price'      => 335000,
                'online_price'        => 353000,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-019',
                'name'                => 'Horn Cover Sprint 2025',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['Sprint 2025'],
                'modal_price'         => 310900,
                'reseller_price'      => 358000,
                'online_price'        => 350000,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-020',
                'name'                => 'Horn Cover Vespa S Facelift',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['S Facelift'],
                'modal_price'         => 346300,
                'reseller_price'      => 398000,
                'online_price'        => 346300,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-021',
                'name'                => 'Horn Cover Vespa S Facelift',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['S Facelift'],
                'modal_price'         => 366300,
                'reseller_price'      => 421000,
                'online_price'        => 366300,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-022',
                'name'                => 'Horn Cover Vespa LX',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['LX'],
                'modal_price'         => 297500,
                'reseller_price'      => 342000,
                'online_price'        => 297500,
                'current_stock'       => 0,
            ],
            [
                'sku'                 => 'FAC-023',
                'name'                => 'Horn Cover Vespa LX',
                'carbon_type'         => 'forged',
                'vespa_compatibility' => ['LX'],
                'modal_price'         => 317500,
                'reseller_price'      => 365000,
                'online_price'        => 317500,
                'current_stock'       => 1,
            ],
            [
                'sku'                 => 'FAC-024',
                'name'                => 'Vespa LX Glovebox Cup',
                'carbon_type'         => 'twill',
                'vespa_compatibility' => ['LX'],
                'modal_price'         => 350000,
                'reseller_price'      => 403000,
                'online_price'        => 350000,
                'current_stock'       => 1,
            ],
        ];

        foreach ($products as $product) {
            Product::create(array_merge($product, [
                'is_active' => true,
                'photo'     => null,
            ]));
        }
    }
}
